# yamllint disable rule:line-length
name: Weekly CI trigger
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'
env:
  BRANCH_NAME: "weekly-ci"
  COMMIT_MESSAGE: "Weekly CI check"
  COMMENT: "[citest]"
  MAIN_BRANCH: "main"
jobs:
  weekly_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create and push empty commit
        run: |
          set -euxo pipefail
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout ${{ env.BRANCH_NAME }} || git checkout -b ${{ env.BRANCH_NAME }}
          git rebase ${{ env.MAIN_BRANCH }}
          git commit --allow-empty -m "${{ env.COMMIT_MESSAGE }}"
          git push -f --set-upstream origin ${{ env.BRANCH_NAME }}

      - name: Create and comment pull request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('making head');
            const head = [context.repo.owner, ":", "${{ env.BRANCH_NAME }}"].join("");
            console.log(head);
            const response = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: head,
              base: context.ref,
              state: "open"
            });
            console.log(response);
            if (response.data.length === 0) {
              const response = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: "${{ env.COMMIT_MESSAGE }}",
                head: "${{ env.BRANCH_NAME }}",
                base: context.ref
              });
            }
            console.log(response);
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: response.data.number,
              body: "${{ env.COMMENT }}",
            });

